### ISSUE TITLE
Karma Tests failed: Use of reserved word 'let' in strict mode

### ISSUE THREAD

**Issue by Zaparix** [bootstrap-vue/bootstrap-vue#1172]
Hi,
I am totally a backend developer and I don't know much about frontend development (but I try to learn it). So I'm sorry, if this question is very stupid 😄 

Before I used this library, I only had Vue and bootstap. But it turns out that this library is very useful for interacting with bootstrap components. So I decided to include bootstrap-vue in my application and everything works fine, except my frontend unit tests.

When I execute the tests, Karma gives me this output:
```
➜  dummy git:(23-web-menu-bar) ✗ npm run unit

> dummy@1.0.0 unit /Users/luca/Projects/dummy
> cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run

07 10 2017 15:27:45.318:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9876/
07 10 2017 15:27:45.321:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
07 10 2017 15:27:45.335:INFO [launcher]: Starting browser PhantomJS
07 10 2017 15:27:46.216:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket VkNWTemJbWakPjrQAAAA with id 38296094
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Use of reserved word 'let' in strict mode
  at webpack:///~/bootstrap-vue/lib/utils/object.js:19:0 <- index.js:251

PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.236 secs / 0 secs)


PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0 secs / 0 secs)


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================

npm ERR! Darwin 16.7.0
npm ERR! argv "/usr/local/Cellar/node/8.0.0/bin/node" "/usr/local/bin/npm" "run" "unit"
npm ERR! node v8.0.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dummy@1.0.0 unit: `cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dummy@1.0.0 unit script 'cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the dummy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dummy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls dummy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/luca/.npm/_logs/2017-10-07T13_27_46_550Z-debug.log
```

**The debug log:**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'unit' ]
2 info using dummy@4.2.0
3 info using node@v8.0.0
4 verbose run-script [ 'preunit', 'unit', 'postunit' ]
5 info lifecycle dummy@1.0.0~preunit: dummy@1.0.0
6 silly lifecycle dummy@1.0.0~preunit: no script for preunit, continuing
7 info lifecycle dummy@1.0.0~unit: dummy@1.0.0
8 verbose lifecycle dummy@1.0.0~unit: unsafe-perm in lifecycle true
9 verbose lifecycle dummy@1.0.0~unit: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/luca/Projects/dummy/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/Cellar/node/8.0.0/bin:/Users/luca/.config/yarn/global/node_modules/.bin
10 verbose lifecycle dummy@1.0.0~unit: CWD: /Users/luca/Projects/dummy
11 silly lifecycle dummy@1.0.0~unit: Args: [ '-c',
11 silly lifecycle   'cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run' ]
12 silly lifecycle dummy@1.0.0~unit: Returned: code: 1  signal: null
13 info lifecycle dummy@1.0.0~unit: Failed to exec unit script
14 verbose stack Error: dummy@1.0.0 unit: `cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:887:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid dummy@1.0.0
16 verbose cwd /Users/luca/Projects/dummy
17 error Darwin 16.7.0
18 error argv "/usr/local/Cellar/node/8.0.0/bin/node" "/usr/local/bin/npm" "run" "unit"
19 error node v8.0.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error dummy@1.0.0 unit: `cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run`
23 error Exit status 1
24 error Failed at the dummy@1.0.0 unit script 'cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the dummy package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env BABEL_ENV=test karma start src/test/webapp/unit/karma.conf.js --single-run
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs dummy
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls dummy
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

I think the relevant lines are:
```
SyntaxError: Use of reserved word 'let' in strict mode
  at webpack:///~/bootstrap-vue/lib/utils/object.js:19:0 <- index.js:251

```

In the file "lib/utils/object.js" of this repository is this line: `let to = Object(target);`
I thought that this could be the error. But maybe there is something wrong with my test?

This is my karma configuration:

```
var webpackConfig = require('../../../../build/webpack.test.conf')

module.exports = function (config) {
  config.set({
    browsers: ['PhantomJS'],
    frameworks: ['mocha', 'sinon-chai', 'phantomjs-shim'],
    reporters: ['spec', 'coverage'],
    files: ['./index.js'],
    preprocessors: {
      './index.js': ['webpack', 'sourcemap']
    },
    webpack: webpackConfig,
    webpackMiddleware: {
      noInfo: true
    },
    coverageReporter: {
      dir: './coverage',
      reporters: [
        { type: 'lcov', subdir: '.' },
        { type: 'text-summary' }
      ]
    }
  })
}
```

My index.js (for unit tests):
```
import Vue from 'vue'

Vue.config.productionTip = false
require('es6-promise').polyfill()

// require all test files (files that ends with .spec.js)
const testsContext = require.context('./specs', true, /\.spec$/)
testsContext.keys().forEach(testsContext)

// require all src files except main.js or html files for coverage.
// you can also change this to match only the subset of files that
// you want coverage for.
const srcContext = require.context('../../../../src/main/webapp', true, /^\.\/(?!((main\.js)|(.*\.html))?$)/)
srcContext.keys().forEach(srcContext)
```
and my test:
```
import Vue from 'vue'
import Home from '@/components/Home'

describe('Home.vue', () => {
  it('should render correct contents', () => {
    const Constructor = Vue.extend(Home)
    const vm = new Constructor().$mount()
    expect(vm.$el.querySelector('.app-home h1').textContent)
      .to.equal('Home')
  })
})
```

The configuration is mostly from the vue webpack sample.

I hope someone can help me 😊

**Comment by tmorehouse** [comment]
Bootstrap vue is written with the latest ES6 JavaScript, and babel converts it (transpiles) from ES6 to standard JavaScript. The keyword `let` (along with `const`) are used extensively through the bootstrap-vue library.

You are probably missing the babel-loader (or required babel options) in your webpack-config.

**Comment by Zaparix** [comment]
I used ES6 in my code, too. So I thought that this can't be the problem... But after I set up babel again, it worked 👍 
Thank you
