### ISSUE TITLE
`babel-plugin-external-helpers` should not be in `devDep`

### ISSUE THREAD

**Issue by Runrioter** [bootstrap-vue/bootstrap-vue#1243]
When I built my project, I got this:
```
 error  in ./~/bootstrap-vue/lib/components/alert.vue

Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "/Users/.../node_modules/bootstrap-vue/lib/.babelrc" at 0, attempted to resolve relative to "/Users/.../node_modules/bootstrap-vue/lib"
    at /Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/.../node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/.../node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/.../node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/.../node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/.../node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/.../node_modules/babel-loader/lib/index.js:175:20)
```

**Comment by tmorehouse** [comment]
Could you provide a sample of your package.json and build information?

**Comment by tmorehouse** [comment]
Are you also importing the full Bootratrp-Vue library, or just importing individual components?

**Comment by Runrioter** [comment]
I set up my repo with vue-cli, and import individual components for my new vue file like this.
```vue
<template>
  <div>
    <b-container class="bv-example-row">
      <b-row>
          <b-col>1 of 3</b-col>
          <b-col>2 of 3</b-col>
          <b-col>3 of 3</b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>

import { bContainer, bRow, bCol } from 'bootstrap-vue/lib/components'

export default {
  components: {
    bContainer,
    bRow,
    bCol
  }
}
</script>

```
When I was running `npm start`, I got error info in terminal.

Thanks @tmorehouse

**Comment by tmorehouse** [comment]
Are you using one of the bootstrap-vue vue-cli webpack templates?  If so, we may need to create a new template for those who import individual components.

**Comment by Runrioter** [comment]
@tmorehouse  currently, will you plan to release `v1.0.0-beta.10`, because when I npmed install bootstrap-vue, I found some bugs had fixed in `dev` branch.

**Comment by tmorehouse** [comment]
Where hoping to have the new release out within the next couple of days.

**Comment by Runrioter** [comment]
Ok, I will close it, if new release works well.

**Comment by tmorehouse** [comment]
New release is now out.

**Comment by Runrioter** [comment]
@tmorehouse  Awesome, thank you.
