### ISSUE TITLE
Error on starting with Nuxt

### ISSUE THREAD

**Issue by cyberiaa** [bootstrap-vue/bootstrap-vue#1546]
Hi-

I get this error on server but not on local machine. 

```
Error: Cannot resolve "bootstrap-vue/nuxt" from "/home/server/bootstrap-vue/nu  xt"

   - nuxt.js:222 Nuxt.resolvePath
    [eden]/[nuxt]/lib/core/nuxt.js:222:11

   - module.js:114 ModuleContainer.addModule
    [eden]/[nuxt]/lib/core/module.js:114:35|

   - utils.js:96 promise.then
   [eden]/[nuxt]/lib/common/utils.js:96:43

  - next_tick.js:228 process._tickDomainCallback
    internal/process/next_tick.js:228:7

  - module.js:686 Function.Module.runMain
    module.js:686:11

  - bootstrap_node.js:187 startup
    bootstrap_node.js:187:16

   - bootstrap_node.js:608
     bootstrap_node.js:608:3
```

Followed by this. The interesting point is there is no direct relation between Nuxt project and /home/server which is API server.
```

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
	Error: Couldn't find a `pages` directory in /home/server. Please create one under the project root
    at Builder.build (/home/eden/node_modules/nuxt/lib/builder/builder.js:147:17)
     at <anonymous>
     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
   at Function.Module.runMain (module.js:686:11)
     at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by cyberiaa** [comment]
I started node instance from project directory and seems this solved the problem.
