### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by michel-fornaris** [bootstrap-vue/bootstrap-vue#1877]
https://bootstrap-vue.js.org/docs/components/table/ table not being displayed in IE11. Is it supposed to work in IE11?

**Comment by Yamakaky** [comment]
Do you have error printed in the dev console?

**Comment by michel-fornaris** [comment]
DOM7011: The code on this page disabled back and forward caching. For more information, see: http://go.microsoft.com/fwlink/?LinkID=291337
table
HTML1300: Navigation occurred.
table
HTML1402: Character reference is missing an ending semicolon ";".
table (1342,144)
HTML1402: Character reference is missing an ending semicolon ";".
table (1359,164)
[vue-analytics] Error in directive play bind hook: Object doesn't support property or method 'includes'
TypeError: Object doesn't support property or method 'includes'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at loadVue (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:10243)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:10640)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:10560)
   at Qn (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:41056)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:40401)
   at Wn (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:40172)
   at m (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:54475)
   at C (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:57586)
   at C (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:57456)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:57813)"
   }
TypeError: Object doesn't support property or method 'includes' [object Object] directive play bind hook
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at loadVue (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:10243)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:10640)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:10560)
   at Qn (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:41056)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:40401)
   at Wn (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:40172)
   at m (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:54475)
   at C (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:57586)
   at C (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:57456)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:57813)"
   }
   {
      [functions]: ,
      $attrs: { },
      $children: [ ],
      $data: { },
      $el: { },
      $ga: { },
      $isServer: false,
      $listeners: { },
      $metaInfo: { },
      $nuxt: { },
      $options: { },
      $parent: { },
      $props: undefined,
      $refs: { },
      $root: { },
      $route: { },
      $router: { },
      $scopedSlots: { },
      $slots: { },
      $ssrContext: undefined,
      $vnode: { },
      __proto__: { },
      _computedWatchers: { },
      _data: { },
      _directInactive: false,
      _events: { },
      _hasHookEvent: false,
      _hasMetaInfo: true,
      _inactive: null,
      _isBeingDestroyed: false,
      _isDestroyed: false,
      _isMounted: false,
      _isVue: true,
      _renderProxy: { },
      _routerRoot: { },
      _self: { },
      _staticTrees: null,
      _uid: 81,
      _vnode: { },
      _watcher: { },
      _watchers: [ ],
      content: <Permission denied>,
      meta: { },
      readme: "<h1 id="tables">Tables</h1>
<blockquote>
<p>For displaying tabular data. <code>&lt;b-table&gt;</code> supports pagination, filtering, sorting,
custom rendering, events, and asynchronous data.</p>
</blockquote>
<p><strong>Example: Basic usage</strong></p>
<pre class="hljs"><span class="hljs-tag">&lt;<span class="hljs-name">template</span>&gt;</span>
  <span class="hljs-tag">&lt;<span class="hljs-name">b-table</span> <span class="hljs-attr">striped</span> <span class="hljs-attr">hover</span> <span class="hljs-attr">:items</span>=<span class="hljs-string">&quot;items&quot;</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name">b-table</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name">template</span>&gt;</span>

<span class="hljs-tag">&lt;<span class="hljs-name">script</span>&gt;</span><span class="javascript">
<span class="hljs-keyword">const</span> items = [
  { <span class="hljs-attr">isActive</span>: <span class="hljs-literal">true</span>, <span class="hljs-attr">age</span>: ",
      scrollTimeout: null
   }
   "directive play bind hook"
[vue-analytics] Error in render: Object doesn't support property or method 'includes'
TypeError: Object doesn't support property or method 'includes'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176556)
   at os.bTable.computed.computedFields (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176530)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe.prototype.evaluate (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:17906)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:19794)
   at os.bTable.render (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:167304)
   at t.prototype._render (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:33509)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:64888)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16657)"
   }

TypeError: Object doesn't support property or method 'includes' [object Object] render
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176556)
   at os.bTable.computed.computedFields (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176530)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe.prototype.evaluate (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:17906)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:19794)
   at os.bTable.render (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:167304)
   at t.prototype._render (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:33509)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:64888)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16657)"
   }
   {
      [functions]: ,
      $attrs: { },
      $children: [ ],
      $data: { },
      $el: { },
      $ga: { },
      $isServer: false,
      $listeners: { },
      $nuxt: { },
      $options: { },
      $parent: { },
      $props: { },
      $refs: { },
      $root: { },
      $route: { },
      $router: { },
      $scopedSlots: { },
      $slots: { },
      $ssrContext: undefined,
      $vnode: { },
      __proto__: { },
      _computedWatchers: { },
      _data: { },
      _directInactive: false,
      _events: { },
      _hasHookEvent: false,
      _inactive: null,
      _isBeingDestroyed: false,
      _isDestroyed: false,
      _isMounted: false,
      _isVue: true,
      _props: { },
      _renderProxy: { },
      _routerRoot: { },
      _self: { },
      _staticTrees: null,
      _uid: 87,
      _vnode: null,
      _watcher: { },
      _watchers: [ ],
      apiUrl: "",
      bodyClasses: [ ],
      bordered: false,
      busy: false,
      caption: null,
      captionStyles: { },
      captionTop: false,
      computedBusy: false,
      computedFields: <Permission denied>,
      computedItems: [ ],
      context: { },
      currentPage: 1,
      dark: false,
      emptyFilteredText: "There are no records matching your request",
      emptyText: "There are no records to show",
      fields: null,
      filter: null,
      filteredItems: [ ],
      fixed: false,
      footClasses: [ ],
      footClone: false,
      footVariant: "",
      hasProvider: false,
      headClasses: [ ],
      headVariant: "default",
      hover: false,
      id: null,
      inverse: null,
      isResponsive: false,
      isStacked: false,
      items: [ ],
      labelSortAsc: "Click to sort Ascending",
      labelSortDesc: "Click to sort Descending",
      localBusy: false,
      localFiltering: true,
      localId_: "__BVID__87",
      localItems: [ ],
      localPaging: true,
      localSortBy: "",
      localSortDesc: false,
      localSorting: true,
      noLocalSorting: false,
      noProviderFiltering: false,
      noProviderPaging: false,
      noProviderSorting: false,
      noSortReset: false,
      outlined: false,
      perPage: 0,
      responsive: false,
      responsiveClass: "",
      showEmpty: false,
      small: true,
      sortBy: null,
      sortCompare: null,
      sortDesc: false,
      sortDirection: "asc",
      stacked: false,
      striped: true,
      tableClasses: [ ],
      tbodyClass: null,
      tbodyTrClass: null,
      tfootClass: null,
      tfootTrClass: null,
      theadClass: null,
      theadTrClass: null,
      value: [ ]
   }
   "render"

[vue-analytics] Error in render: Object doesn't support property or method 'includes'

TypeError: Object doesn't support property or method 'includes'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176556)
   at os.bTable.computed.computedFields (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176530)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe.prototype.evaluate (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:17906)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:19794)
   at os.bTable.render (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:167304)
   at t.prototype._render (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:33509)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:64888)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe.prototype.run (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:17645)"
   }

TypeError: Object doesn't support property or method 'includes' [object Object] render
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176556)
   at os.bTable.computed.computedFields (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:176530)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe.prototype.evaluate (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:17906)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:19794)
   at os.bTable.render (https://bootstrap-vue.js.org/_nuxt/d3224c08ef4eec0cf0e7.js:1:167304)
   at t.prototype._render (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:33509)
   at Anonymous function (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:64888)
   at Pe.prototype.get (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:16758)
   at Pe.prototype.run (https://bootstrap-vue.js.org/_nuxt/1b6a54a350bfda3bf9c2.js:2:17645)"
   }
   {
      [functions]: ,
      $attrs: { },
      $children: [ ],
      $data: { },
      $el: { },
      $ga: { },
      $isServer: false,
      $listeners: { },
      $nuxt: { },
      $options: { },
      $parent: { },
      $props: { },
      $refs: { },
      $root: { },
      $route: { },
      $router: { },
      $scopedSlots: { },
      $slots: { },
      $ssrContext: undefined,
      $vnode: { },
      __BV_root_listeners__: [ ],
      __proto__: { },
      _computedWatchers: { },
      _data: { },
      _directInactive: false,
      _events: { },
      _hasHookEvent: false,
      _inactive: null,
      _isBeingDestroyed: false,
      _isDestroyed: false,
      _isMounted: true,
      _isVue: true,
      _props: { },
      _renderProxy: { },
      _routerRoot: { },
      _self: { },
      _staticTrees: null,
      _uid: 87,
      _vnode: { },
      _watcher: { },
      _watchers: [ ],
      apiUrl: "",
      bodyClasses: [ ],
      bordered: false,
      busy: false,
      caption: null,
      captionStyles: { },
      captionTop: false,
      computedBusy: false,
      computedFields: <Permission denied>,
      computedItems: [ ],
      context: { },
      currentPage: 1,
      dark: false,
      emptyFilteredText: "There are no records matching your request",
      emptyText: "There are no records to show",
      fields: null,
      filter: null,
      filteredItems: [ ],
      fixed: false,
      footClasses: [ ],
      footClone: false,
      footVariant: "",
      hasProvider: false,
      headClasses: [ ],
      headVariant: "default",
      hover: false,
      id: null,
      inverse: null,
      isResponsive: false,
      isStacked: false,
      items: [ ],
      labelSortAsc: "Click to sort Ascending",
      labelSortDesc: "Click to sort Descending",
      localBusy: false,
      localFiltering: true,
      localId_: "__BVID__87",
      localItems: [ ],
      localPaging: true,
      localSortBy: null,
      localSortDesc: false,
      localSorting: true,
      noLocalSorting: false,
      noProviderFiltering: false,
      noProviderPaging: false,
      noProviderSorting: false,
      noSortReset: false,
      outlined: false,
      perPage: 0,
      responsive: false,
      responsiveClass: "",
      showEmpty: false,
      small: true,
      sortBy: null,
      sortCompare: null,
      sortDesc: false,
      sortDirection: "asc",
      stacked: false,
      striped: true,
      tableClasses: [ ],
      tbodyClass: null,
      tbodyTrClass: null,
      tfootClass: null,
      tfootTrClass: null,
      theadClass: null,
      theadTrClass: null,
      value: [ ]
   }
   "render"

**Comment by mosinve** [comment]
Unfortunately, i don't have an IE11, so can you test this branch for errors https://github.com/bootstrap-vue/bootstrap-vue/tree/fix-compatibility-ie11 ?

**Comment by michel-fornaris** [comment]
@mosinve I will try that branch, thanks

**Comment by mosinve** [comment]
@michel-fornaris Hi, have you checked that branch? Issue resolved?

**Comment by michel-fornaris** [comment]
No, I will check it today. Sorry but I've been very busy :(

**Comment by michel-fornaris** [comment]
I included the CSS and JS in a regular HTML page including the babel polyfill //unpkg.com/babel-polyfill@latest/dist/polyfill.min.js and tested in IE11 and everything looks working fine. We can consider this as resolved.
