### ISSUE TITLE
Vue packages version mismatch

### ISSUE THREAD

**Issue by shaneparsons** [bootstrap-vue/bootstrap-vue#2567]
I just swapped the dev branch for RC 12 in a Laravel / Vue project of mine, and I'm now getting this when I run `npm run dev`:

```bash
ERROR in ./resources/js/views/App.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.6
- vue-template-compiler@2.5.22

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/app.js 23:0-30 55:9-12
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/Dashboard.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.6
- vue-template-compiler@2.5.22

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/app.js 24:0-42 37:15-24
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/vue-full-calendar/components/FullCalendar.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.6
- vue-template-compiler@2.5.22

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./node_modules/vue-full-calendar/index.js 1:0-56 5:39-51 8:0-23
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/Register.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.6
- vue-template-compiler@2.5.22

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/app.js 26:0-40 45:15-23
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/Playground.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.6
- vue-template-compiler@2.5.22

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/app.js 25:0-44 41:15-25
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/SignIn.vue
Module Error (from ./node_modules/vue-loader/lib/index.js):


Vue packages version mismatch:

- vue@2.6.6
- vue-template-compiler@2.5.22

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

 @ ./resources/js/app.js 27:0-36 49:15-21
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../lib/bootstrap-vue/dist/bootstrap-vue.css' in '/Users/30ptdesign/Code/sred-logbook/resources/sass'
    at factory.create (/Users/30ptdesign/Code/sred-logbook/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/30ptdesign/Code/sred-logbook/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/30ptdesign/Code/sred-logbook/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/30ptdesign/Code/sred-logbook/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/30ptdesign/Code/sred-logbook/node_modules/neo-async/async.js:2825:7
    at /Users/30ptdesign/Code/sred-logbook/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/30ptdesign/Code/sred-logbook/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn43 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:24:1)
    at hook.callAsync (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/30ptdesign/Code/sred-logbook/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at fs.stat (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at process.nextTick (/Users/30ptdesign/Code/sred-logbook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:61:11)
 @ ./resources/sass/app.scss

ERROR in ./resources/js/views/App.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/30ptdesign/Code/sred-logbook/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/30ptdesign/Code/sred-logbook/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 23:0-30 55:9-12
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/Register.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/30ptdesign/Code/sred-logbook/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/30ptdesign/Code/sred-logbook/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 26:0-40 45:15-23
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/Playground.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/30ptdesign/Code/sred-logbook/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/30ptdesign/Code/sred-logbook/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 25:0-44 41:15-25
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/Dashboard.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/30ptdesign/Code/sred-logbook/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/30ptdesign/Code/sred-logbook/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 24:0-42 37:15-24
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./node_modules/vue-full-calendar/components/FullCalendar.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/30ptdesign/Code/sred-logbook/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/30ptdesign/Code/sred-logbook/node_modules/vue-loader/lib/index.js:67:22)
 @ ./node_modules/vue-full-calendar/index.js 1:0-56 5:39-51 8:0-23
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/js/views/SignIn.vue
Module build failed (from ./node_modules/vue-loader/lib/index.js):
TypeError: Cannot read property 'parseComponent' of undefined
    at parse (/Users/30ptdesign/Code/sred-logbook/node_modules/@vue/component-compiler-utils/dist/parse.js:14:23)
    at Object.module.exports (/Users/30ptdesign/Code/sred-logbook/node_modules/vue-loader/lib/index.js:67:22)
 @ ./resources/js/app.js 27:0-36 49:15-21
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss)
Module not found: Error: Can't resolve '../lib/bootstrap-vue/dist/bootstrap-vue.css' in '/Users/30ptdesign/Code/sred-logbook/resources/sass'
 @ ./resources/sass/app.scss (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-4!./node_modules/sass-loader/lib/loader.js??ref--5-5!./resources/sass/app.scss) 3:10-171
 @ ./resources/sass/app.scss
```

It seems like it's probably an easy fix, but I wanted to run it by you guys.

**Comment by shaneparsons** [comment]
I think some links probably just need updating... I'll see what I can do and reopen this if neccessary.

**Comment by XpamAmAdEuS** [comment]
- vue@2.6.6
- vue-template-compiler@2.5.22
This two packages need to be same version.

**Comment by tmorehouse** [comment]
@shaneparsons Did you find a solution?

**Comment by shaneparsons** [comment]
Yeah it's all good now thanks! Here's what I did:
- set `vue` and `vue-template-compiler` to the same version
- fix broken link in local scss

**Comment by tmorehouse** [comment]
In Bootstrap-Vue 2.0.0-rc.12 `devDependencies`:

```js
    "vue": "^2.6.6",
    "vue-jest": "^3.0.3",
    "vue-server-renderer": "^2.6.6",
    "vue-template-compiler": "^2.6.6"
```

Both Vue and template compiler are set to the same version...

**Comment by shaneparsons** [comment]
Yeah, my local package.json had mismatches though. It never complained about it until now though, which is strange.

**Comment by tmorehouse** [comment]
Yeah... weird.
