### ISSUE TITLE
IE11 support for tooltip (Sentry error)

### ISSUE THREAD

**Issue by mauxtin** [bootstrap-vue/bootstrap-vue#2713]
- Operating system and version: **Windows 10**
- Browser and version: IE11.0
- Version of BootstrapVue that you are using: 2.0.0-rc.13

I am getting the following error on Sentry and the tooltip doesn't appear.
```
TypeError bootstrap-vue/es/utils/dom in e.isDisabled

TypeError: Unable to get property 'contains' of undefined or null reference
  at e.isDisabled(./node_modules/bootstrap-vue/es/utils/dom.js:88:1)
  at value(./node_modules/bootstrap-vue/es/utils/tooltip.class.js:752:1)
  at r(./node_modules/@sentry/browser/dist/index.js:3208:1)
  at r(./node_modules/@sentry/browser/dist/index.js:3208:1)
  at r(./node_modules/@sentry/browser/dist/index.js:3208:1)
  at r(./node_modules/@sentry/browser/dist/index.js:3208:1)
```

This is how I am using the tooltip. Basically I have an svg icon that opens a tooltip on hover.
```
<template>
  <svg 
    v-b-tooltip.hover 
    id="verified_icon" 
    :title="$t('store.verified')" 
    :width="size +'px'" 
    :height="size +'px'" 
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    version="1.1" 
    x="0px" 
    y="0px" 
    viewBox="0 0 512 512" 
    style="enable-background:new 0 0 512 512;" 
    xml:space="preserve" 
    class=""><g><g><g><path 
      d="M437.019,74.98C388.667,26.629,324.38,0,256,0C187.619,0,123.332,26.629,74.98,74.98C26.629,123.332,0,187.62,0,256    s26.629,132.667,74.98,181.019C123.332,485.371,187.62,512,256,512s132.667-26.629,181.019-74.98    C485.371,388.667,512,324.38,512,256S485.371,123.333,437.019,74.98z M378.306,195.073L235.241,338.139    c-2.929,2.929-6.768,4.393-10.606,4.393c-3.839,0-7.678-1.464-10.607-4.393l-80.334-80.333c-5.858-5.857-5.858-15.354,0-21.213    c5.857-5.858,15.355-5.858,21.213,0l69.728,69.727l132.458-132.46c5.857-5.858,15.355-5.858,21.213,0    C384.164,179.718,384.164,189.215,378.306,195.073z" 
      data-original="#000000" 
      class="active-path" 
      data-old_color="#f9bc02" 
      fill="#f9bc02"/></g></g></g> </svg>
</template>
```

**Comment by jackmu95** [comment]
@mauxtin IE 11 returns `undefined` for `el.classList` for SVG elements.

Ref: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/1173756/
