### ISSUE TITLE
I could not use b-pagination in IE 11.

### ISSUE THREAD

**Issue by niyocchan** [bootstrap-vue/bootstrap-vue#3226]
### Describe the bug
I use b-pagination in IE 11.
It happen the following error when I push paging button.

Object doesn't support property or method 'from'

### Steps to reproduce the bug

1. Go to the page
2. Click on number button
3. See error

### Expected behavior

Sorry, I could not find.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.19
- Bootstrap: 4.1.3
- Vue: 3.4.0

**Environment:**

- Device: DELL PC
- OS: Windows10
- Browser: IE11
- Version: 11.437.17763.0

### Additional context
It is no problem in chrom or IE edge.

**Comment by tmorehouse** [comment]
Are you loading hte apropriate polytfills needed for IE 11 support?

https://bootstrap-vue.js.org/docs#js

**Comment by niyocchan** [comment]
Thank you for your reply. 
I tried importing the target library, but the event did not change. 
I will send you the details. Please confirm.

browzer error
```
TypeError: Object doesn't support property or method 'from'
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError",
         Symbol()_i.q5si3h24v2c: undefined,
         Symbol(react.element)_h.q5si3h24v2c: undefined
      },
      description: "Object doesn't support property or method 'from'",
      message: "Object doesn't support property or method 'from'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'from'
   at _iterableToArray (http://localhost:3000/_nuxt/vendors.app.js:18423:137)
   at _toConsumableArray (http://localhost:3000/_nuxt/vendors.app.js:18419:36)
   at Anonymous function (http://localhost:3000/_nuxt/vendors.app.js:18566:9)
   at onClick (http://localhost:3000/_nuxt/vendors.app.js:18563:8)
   at invokeWithErrorHandling (http://localhost:3000/_nuxt/commons.app.js:14239:5)
   at invoker (http://localhost:3000/_nuxt/commons.app.js:14564:7)
   at original._wrapper (http://localhost:3000/_nuxt/commons.app.js:19287:9)",
      Symbol()_i.q5si3h24v2c: undefined,
      Symbol(react.element)_h.q5si3h24v2c: undefined
   }
```
package.json
```
"browserslist": [
    "last 2 version",
    "IE 11"
  ],
  "dependencies": {
    "@babel/polyfill": "^7.4.4",
    "@babel/preset-env": "^7.4.4",
    "@fortawesome/fontawesome-free-webfonts": "^1.0.9",
    "@fortawesome/fontawesome-svg-core": "^1.2.15",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@fortawesome/vue-fontawesome": "^0.1.5",
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/moment": "^1.2.0",
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.0.0-rc.12",
    "chart.js": "^2.7.3",
    "cross-env": "^5.2.0",
    "moment": "^2.24.0",
    "mutationobserver-shim": "^0.3.3",
    "node-sass": "^4.11.0",
    "nuxt": "^2.4.0",
    "nuxt-fontawesome": "^0.4.0",
    "sass-loader": "^7.1.0",
    "url-search-params-polyfill": "^6.0.0",
    "vue-chartjs": "^3.4.0",
    "vuex-persistedstate": "^2.5.4"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^0.0.1",
    "@vue/test-utils": "^1.0.0-beta.29",
    "babel-eslint": "^8.2.1",
    "eslint": "^5.0.1",
    "eslint-config-standard": ">=12.0.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": ">=2.14.0",
    "eslint-plugin-jest": ">=21.24.1",
    "eslint-plugin-node": ">=7.0.1",
    "eslint-plugin-promise": ">=4.0.1",
    "eslint-plugin-standard": ">=4.0.0",
    "eslint-plugin-vue": "^5.0.0",
    "jest": "^24.7.1",
    "lodash.clonedeep": "^4.5.0",
    "nodemon": "^1.18.9"
  }
```

nuxt.config.js
```
 babel: {
    presets: [
      [
        '@babel/preset-env',
        {
          targets: { ie: 11, uglify: true },
          useBuiltIns: true
        }
      ]
    ],
    plugins: [
      '@babel/transform-runtime',
      '@babel/plugin-syntax-dynamic-import'
    ]
  },
  vendor: [ 'babel-polyfill' ],
```

**Comment by tmorehouse** [comment]
I would run `yarn upgrade` (if using yarn) to get the latest package versions (you have quite a few old ones in your dependencies):

```
    "bootstrap": "^4.3.1",
    "bootstrap-vue": "^2.0.0-rc.19",
    "nuxt": "^2.6.3",
```

**Comment by niyocchan** [comment]
Thank you for your reply.
I runed yarn upgrade or I runed yarn install after delete node_modules folder.
but the event did not change.

**Comment by tmorehouse** [comment]
You may need to include a polyfill like https://polyfill.io for IE11, as babel polyfill doesn't patch all IE 11 issues.

**Comment by tasaka-degi** [comment]
Thank you for your reply.
It was solved in the following.

nuxt.config.js
```
head:{
    script: [      
      { src: '//polyfill.io/v3/polyfill.min.js?features=es5%2Ces2015%2CArray.from' }
    ],
  },
```
