### ISSUE TITLE
tabs/tab: Uncaught TypeError: Cannot create property 'true' on string 'active'

### ISSUE THREAD

**Issue by MehrCurry** [bootstrap-vue/bootstrap-vue#34]
After Upgrading to 0.3.10 i get execptions when i click a tab to activate it:

```
TypeError: Cannot create property 'true' on string 'active'
    at VueComponent.set$1 [as $set] (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:825:14)
    at VueComponent.setActive (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:71:1), <anonymous>:1:28372)
    at VueComponent.boundFn [as setActive] (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:126:14)
    at VueComponent.mounted (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:71:1), <anonymous>:1:28596)
    at callHook (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:2479:19)
    at Object.insert (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:2671:5)
    at invokeInsertHook (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:4326:28)
    at Vue$3.patch [as __patch__] (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:4473:5)
    at Vue$3.Vue._update (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:2359:19)
    at Vue$3.eval (eval at <anonymous> (http://localhost:63342/hello/dist/build.js:84:1), <anonymous>:2333:10)
```

**Comment by JanBurp** [comment]
+1

**Comment by pi0** [comment]
@MehrCurry @JanBurp I'll investigate problem soon. thanks for reports.

**Comment by mathlet0x** [comment]
@MehrCurry @JanBurp this issue has been solved, i close it.

**Comment by JanBurp** [comment]
thanks
