### ISSUE TITLE
Clicking  or dbl clicking b-table row causes error on IE

### ISSUE THREAD

**Issue by adholland** [bootstrap-vue/bootstrap-vue#4805]
Using version 2.2.0 there is an issue with b-table on IE 11.

Using IE 11 and attempting a click or double click a row you then see the following - a single error for each click or dbl click. 

Note: due to the error the event does not complete.

```
TypeError: Object expected
{
[functions]: ,
proto: { },
description: "Object expected",
message: "Object expected",
name: "TypeError",
number: -2146823281,
stack: "TypeError: Object expected
at Gy.methods.getTbodyTrs (http://localhost:5000/js/fileManager-legacy.js:23:360432)
at Gy.methods.getTbodyTrIndex (http://localhost:5000/js/fileManager-legacy.js:23:360632)
at Gy.methods.emitTbodyRowEvent (http://localhost:5000/js/fileManager-legacy.js:23:360747)
at Gy.methods.onTBodyRowClicked (http://localhost:5000/js/fileManager-legacy.js:23:361573)
at ne (http://localhost:5000/js/fileManager-legacy.js:7:11658)
at n (http://localhost:5000/js/fileManager-legacy.js:7:13477)
at o._wrapper (http://localhost:5000/js/fileManager-legacy.js:7:51753)",
Symbol()_9.of693fu6u31: undefined
}
```

**Comment by adholland** [comment]
This issue is realted to #4384.

**Comment by adholland** [comment]
Could someone please advise of a possible workaround?

**Comment by tmorehouse** [comment]
Could you provide a simple markup of your table that reproduces the error?

**Comment by tmorehouse** [comment]
I am unable to reproduce this error in IE 11

**Comment by adholland** [comment]
@tmorehouse Thanks for looking into it. I'll try and put something together.

**Comment by adholland** [comment]
I wrote a cut down test case and was not able to reproduce the issue at this time - so I need to investigate further. As a result I'm closing this defect for now.

Thanks for the help.
