### ISSUE TITLE
IE using @click.prevent fails with TypeError: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by jfarraraains** [bootstrap-vue/bootstrap-vue#5029]
### Describe the bug

This bug occurs in either the <b-nav-item/> or the <b-dropdown-item/> tags.

### Steps to reproduce the bug

1. Use either the b-nave-item or b-dropdown-item tag with the @click.prevent tag.
2. Run built code in IE
3. code fails with message in console: TypeError: Object doesn't support property or method 'from'

### Expected behavior

IE to run like modern browsers.

### Versions

**Libraries:**

- BootstrapVue: 2.5.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

- Browser: IE
- Version: 11

### Additional context

Here is the detailed item from IE Dev Tools console.

TypeError: Object doesn't support property or method 'from'
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: { },
         message: "",
         name: "TypeError"
      },
      description: "Object doesn't support property or method 'from'",
      message: "Object doesn't support property or method 'from'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'from'
   at Mn (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:23:47455)
   at En (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:23:47239)
   at Anonymous function (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:23:49541)
   at Anonymous function (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:50:43980)
   at Anonymous function (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:1:4795)
   at methods.onClick (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:23:49479)
   at ne (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:7:11658)
   at n (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:7:13477)
   at o._wrapper (https://cp-aains.dev-online.aains.com/js/chunk-vendors.bef7ff2d.js:7:51749)"
   }

**Comment by tmorehouse** [comment]
Sounds like you are not including the required polyfills for IE 11.

- https://bootstrap-vue.js.org/docs#browser-support
- https://bootstrap-vue.js.org/docs#browser

**Comment by jfarraraains** [comment]
We tried these guides but it still did not work for us. We had to replace with vanilla JS for this time.

**Comment by tmorehouse** [comment]
Just make sure the polyfills are loaded _before_ BootstrapVue is loaded.
