### ISSUE TITLE
A tricky problem in server-side rendering feature

### ISSUE THREAD

**Issue by Astrian** [bootstrap-vue/bootstrap-vue#5351]
### Describe the bug

I want to add server-side rendering feature to my existing Vue Cli project with `bootstrap-vue`. There is a error descriped as `ReferenceError: window is not defined` point out that `bootstrap` may used `window` object and not processed properly after I complete operations with mannuals (for SSR feature-relative project).

Error stack: 

```
ReferenceError: window is not defined
    at Object. (/Users/astrian/projects/sandbox/node_modules/mutationobserver-shim/dist/mutationobserver.min.js:12:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at r (/Users/astrian/projects/sandbox/node_modules/vue-server-renderer/build.dev.js:9315:16)
    at Object.mutationobserver-shim (webpack:/external "mutationobserver-shim":1:0)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../src/main.js (js/app.js:3140:79)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Module../src/entry-server.js (js/app.js:3068:63)
    at __webpack_require__ (webpack/bootstrap:19:0)
    at Object.0 (js/app.js:3834:18)
```

### Steps to reproduce the bug

1. Make a Vue Cli project with `bootstrap-vue` plugin
2. Config server-side rendering with `vue-server-renderer` (btw. I wish to use [this plugin](https://vue-cli-plugin-ssr.netlify.app) which also used `vue-server-render`.)
3. `yarn ssr:serve`, visit the demo address, and ta-da! You got the error on browser.

I have tried to create a new (initial) project, config SSR feature which is worked in initial project, and copy my code and paste to the initial project, and the problem is not resolved.

### Expected behavior

The server can render page, and project running normally and can be visited in browser finally.

### Versions

**Libraries:**

- BootstrapVue: 2.14.0
- Bootstrap: 4.4.1
- Vue: 2.6.11

**Environment:**

This is a server-side related problem, so it cannot be resolved by changing devices, OSes or browsers.

### Demo link

Well... No any links... 😂 May you can try to create a blank Vue Cli project to have a try.

### Additional context

I think it is a problem occured by Bootstrap not BootstrapVue, but maybe (only) BootstrapVue can have some solutions to resolve it?

**Comment by tmorehouse** [comment]
It looks like it might be an issue with `mutationobserver-shim`.  Are you using the latest version of the shim?

**Comment by tmorehouse** [comment]
Although you really shouldn't need the mutationobserver shim, as the majority of browsers BootstrapVue supports have mutation observer support.

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver#Browser_compatibility

**Comment by Astrian** [comment]
@tmorehouse I see, let me check `mutationobserver-shim` first. It installed by other depency(-ies) and I will check the lastest version.

**Comment by tmorehouse** [comment]
The shim is only required for IE10 and lower (and some older other browsers).  BootstrapVue doesn't support IE 10 or lower.

**Comment by Astrian** [comment]
@tmorehouse Thanks for reply and extra diagnosis, I will check for which package used the `mutationobserver-shim` (which is looks like a huge work...)
