### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by gabrielbuzziv** [bootstrap-vue/bootstrap-vue#7]
[Error: ./~/bootstrap-vue/dist/bootstrapVue.common.js
Module build failed: SyntaxError: 'with' in strict mode (1:2509)
    at Parser.pp$4.raise (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp$1.parseWithStatement (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:932:27)
    at Parser.pp$1.parseStatement (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:708:32)
    at Parser.pp$1.parseBlock (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$3.parseFunctionBody (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:2105:24)
    at Parser.pp$1.parseFunction (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1065:10)
    at Parser.pp$3.parseExprAtom (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1810:19)
    at Parser.parseExprAtom (/var/www/vuejs/node_modules/buble/dist/buble.umd.js:656:26)
    at Parser.pp$3.parseExprSubscripts (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1692:19)
 @ ./resources/assets/js/main.js 5:0-40]
  message: './~/bootstrap-vue/dist/bootstrapVue.common.js\nModule build failed: SyntaxError: \'with\' in strict mode (1:2509)\n    at Parser.pp$4.raise (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:2221:15)\n    at Parser.pp$1.parseWithStatement (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:932:27)\n    at Parser.pp$1.parseStatement (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:708:32)\n    at Parser.pp$1.parseBlock (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:981:25)\n    at Parser.pp$3.parseFunctionBody (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:2105:24)\n    at Parser.pp$1.parseFunction (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1065:10)\n    at Parser.pp$3.parseExprAtom (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1810:19)\n    at Parser.parseExprAtom (/var/www/vuejs/node_modules/buble/dist/buble.umd.js:656:26)\n    at Parser.pp$3.parseExprSubscripts (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1715:21)\n    at Parser.pp$3.parseMaybeUnary (/var/www/vuejs/node_modules/buble/node_modules/acorn/dist/acorn.js:1692:19)\n @ ./resources/assets/js/main.js 5:0-40',
  showStack: false,
  showProperties: true,
  plugin: 'webpack-stream',
  __safety: { toString: [Function: bound ] } }

**Comment by pi0** [comment]
@gabrielbuzziv This is because you are trying to Bundle, The bundled version again ;) in your case you can either ignore `node_modules` inside loader or easily use `boootstrap-vue/components` directly ...

**Comment by gabrielbuzziv** [comment]
@pi0  So i don't need to do this in my main.js?
Import BootstrapVue from 'bootstrap-vue'

Sorry, i'm still studying vue and node.

**Comment by gabrielbuzziv** [comment]
Got it, thanks :D
