### ISSUE TITLE
Cannot run yarn docs-dev

### ISSUE THREAD

**Issue by LLyaudet** [bootstrap-vue/bootstrap-vue#7072]
### Describe the bug

Hello,

Thanks for your work :)

I'm trying to contribute to boostrap-vue because I want to add a feature "lazy" on v-b-tooltip 
similar to the feature lazy on b-dropdown.
I'm doing what is wrote in CONTRIBUTING.md
But some steps fail on latest Ubuntu 22.10.

Detail : 
When running the command :

`yarnpkg docs-dev`

I get multiple errors. (I'm on latest Ubuntu 22.10 and yarn is named yarnpkg on it.)
I solved the first error : 

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/NormalModule.js:471:10)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/NormalModule.js:503:5
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/NormalModule.js:358:12
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

by adding  `     config.output.hashFunction = 'sha512'`  in nuxt.config.js : 

```
    extend(config, { isDev, loaders }) {
      config.resolve.alias.vue = 'vue/dist/vue.common'

      config.resolveLoader.alias = config.resolveLoader.alias || {}
      config.resolveLoader.alias['marked-loader'] = path.join(__dirname, './utils/marked-loader')
      config.resolveLoader.alias['docs-loader'] = path.join(__dirname, './utils/docs-loader')

      // Source maps make the bundles monstrous, do leave it off in prod mode
      if (isDev) {
        config.devtool = 'eval-source-map'
      }

      config.output.hashFunction = 'sha512'
```
I do not claim that sha512 is the best choice.
It is just a choice I made for fast solving of the error.
md4 was deprecated of OpenSSL hence the error in the first place.

But now I have another error :

```
/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/html-webpack-plugin/lib/child-compiler.js:190
    return childCompilation.assets[helperFileName].source();
                                                   ^

TypeError: Cannot read properties of undefined (reading 'source')
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/html-webpack-plugin/lib/child-compiler.js:190:52
    at Array.map (<anonymous>)
    at extractHelperFilesFromCompilation (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/html-webpack-plugin/lib/child-compiler.js:189:43)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/html-webpack-plugin/lib/child-compiler.js:113:13
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compiler.js:343:11
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compiler.js:681:15
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compiler.js:678:31
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1423:35
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1414:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1409:36
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1405:32
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1342:27)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compiler.js:675:18
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1253:28)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1185:12
    at /mnt/0e97ab55-5a13-41db-b8bf-bbbe664691f1/home/laurent/ReposGit/bootstrap-vue/node_modules/webpack/lib/Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v18.7.0
error Command failed with exit code 1.
```                           

I am trying my best but clearly nodejs dependencies took dependency hell to a whole new level ;) XD
Thanks for your help :), best regards,
    Laurent Lyaudet

### Steps to reproduce the bug

Do the commands in CONTRIBUTING.md on latest Ubuntu 22.10.

### Expected behavior

I wanted a working dev env to enhance bootstrap-vue and debug it in my app.

### Versions

**Libraries:**

- BootstrapVue: 2.#.# N/A
- Bootstrap: 4.#.# N/A
- Vue: 2.#.# N/A
latest git clone/git pull

**Environment:**

- Device: Laptop
- OS: Ubuntu 22.10
- Browser: N/A
- Version: N/A

**Comment by LLyaudet** [comment]
I forgot to say that there is also a minor issue with previous command: 

`yarn install`

I had an error and to fix it I did:

`rm -f yarn.lock`

and then again:

`yarn install`

**Comment by xanf** [comment]
@LLyaudet you might need to downgrade node.js to 16.x

**Comment by pedropcamellon** [comment]
Windows 11 - 23H2
Nodejs: 20.16.0
Npm: 10.8.1

After I upgrade to nodejs 20 I'm getting the same errors on my project. Im stuck here: "return childCompilation.assets[helperFileName].source();"

- I removed the ".lock" file, then npm i. It did not solve the issue.
- Downgrade node.js to 16.x is not an option for me.

Any ideas?
